# file generated by vcs-versioning
# don't change, don't track in version control
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = '0.1.0.dev145+gfbc7dff35.d20260607'
__version_tuple__ = version_tuple = (0, 1, 0, 'dev145', 'gfbc7dff35.d20260607')

__commit_id__ = commit_id = 'gfbc7dff35'
