[pytest]
addopts = -q
testpaths = tests
norecursedirs =
    .git
    .github
    .trunk
    __pycache__
    .pytest_cache
    .mypy_cache
    .ruff_cache
    build
    dist
    release_tmp
    tmp
    temp